import type { Module, Section } from "./types";

export const TAKSHA_MODULES: Module[] = [
  {
    id: "M01-workshop-safety",
    title_en: "Workshop Safety and Work Discipline",
    title_bn: "Workshop Safety and Work Discipline",
    title_hi: "Workshop Safety and Work Discipline",
    icon: "🛡️",
    sort_order: 1,
    theory_hours: 3,
    practical_hours: 5,
    group_key: "foundation",
    group_label_en: "Foundation",
    group_label_bn: "Foundation",
    group_label_hi: "Foundation",
  },
  {
    id: "M02-tools",
    title_en: "Hand Tools, Power Tools, and Maintenance",
    title_bn: "Hand Tools, Power Tools, and Maintenance",
    title_hi: "Hand Tools, Power Tools, and Maintenance",
    icon: "🧰",
    sort_order: 2,
    theory_hours: 4,
    practical_hours: 8,
    group_key: "foundation",
    group_label_en: "Foundation",
    group_label_bn: "Foundation",
    group_label_hi: "Foundation",
  },
  {
    id: "M03-measure-mark",
    title_en: "Measurement, Marking, and Layout",
    title_bn: "Measurement, Marking, and Layout",
    title_hi: "Measurement, Marking, and Layout",
    icon: "📏",
    sort_order: 3,
    theory_hours: 4,
    practical_hours: 8,
    group_key: "foundation",
    group_label_en: "Foundation",
    group_label_bn: "Foundation",
    group_label_hi: "Foundation",
  },
  {
    id: "M04-wood-materials",
    title_en: "Wood Types, Boards, Hardware, and Adhesives",
    title_bn: "Wood Types, Boards, Hardware, and Adhesives",
    title_hi: "Wood Types, Boards, Hardware, and Adhesives",
    icon: "🪵",
    sort_order: 4,
    theory_hours: 5,
    practical_hours: 6,
    group_key: "materials",
    group_label_en: "Materials",
    group_label_bn: "Materials",
    group_label_hi: "Materials",
  },
  {
    id: "M05-cutting-joining",
    title_en: "Cutting, Shaping, and Joinery",
    title_bn: "Cutting, Shaping, and Joinery",
    title_hi: "Cutting, Shaping, and Joinery",
    icon: "🪚",
    sort_order: 5,
    theory_hours: 5,
    practical_hours: 12,
    group_key: "core_skills",
    group_label_en: "Core Skills",
    group_label_bn: "Core Skills",
    group_label_hi: "Core Skills",
  },
  {
    id: "M06-furniture-basics",
    title_en: "Furniture Frames, Cabinets, and Drawers",
    title_bn: "Furniture Frames, Cabinets, and Drawers",
    title_hi: "Furniture Frames, Cabinets, and Drawers",
    icon: "🪑",
    sort_order: 6,
    theory_hours: 5,
    practical_hours: 14,
    group_key: "core_skills",
    group_label_en: "Core Skills",
    group_label_bn: "Core Skills",
    group_label_hi: "Core Skills",
  },
  {
    id: "M07-finishing",
    title_en: "Sanding, Finishing, Polishing, and Protection",
    title_bn: "Sanding, Finishing, Polishing, and Protection",
    title_hi: "Sanding, Finishing, Polishing, and Protection",
    icon: "🎨",
    sort_order: 7,
    theory_hours: 4,
    practical_hours: 10,
    group_key: "finishing",
    group_label_en: "Finishing",
    group_label_bn: "Finishing",
    group_label_hi: "Finishing",
  },
  {
    id: "M08-site-installation",
    title_en: "Site Work, Installation, and Client Handover",
    title_bn: "Site Work, Installation, and Client Handover",
    title_hi: "Site Work, Installation, and Client Handover",
    icon: "🏗️",
    sort_order: 8,
    theory_hours: 4,
    practical_hours: 10,
    group_key: "field_work",
    group_label_en: "Field Work",
    group_label_bn: "Field Work",
    group_label_hi: "Field Work",
  },
  {
    id: "M09-repair",
    title_en: "Repair, Restoration, and Problem Solving",
    title_bn: "Repair, Restoration, and Problem Solving",
    title_hi: "Repair, Restoration, and Problem Solving",
    icon: "🔧",
    sort_order: 9,
    theory_hours: 4,
    practical_hours: 10,
    group_key: "field_work",
    group_label_en: "Field Work",
    group_label_bn: "Field Work",
    group_label_hi: "Field Work",
  },
  {
    id: "M10-advanced-craft",
    title_en: "Advanced Craftsmanship and Professional Practice",
    title_bn: "Advanced Craftsmanship and Professional Practice",
    title_hi: "Advanced Craftsmanship and Professional Practice",
    icon: "🏆",
    sort_order: 10,
    theory_hours: 5,
    practical_hours: 16,
    group_key: "professional",
    group_label_en: "Professional",
    group_label_bn: "Professional",
    group_label_hi: "Professional",
  },
];

const moduleBodies: Record<string, string> = {
  "M01-workshop-safety": "Learn safe workshop habits before touching any tool: PPE, dust control, machine guards, cable discipline, sharp-tool handling, fire safety, first aid, and clean work zones.\n\nObjectives:\n- Identify common workshop hazards.\n- Use eye, ear, hand, and respiratory protection correctly.\n- Set up a clean bench and safe material flow.\n\nPractical exercise: inspect a workbench, list five hazards, correct them, and explain the safety reason for each correction.\n\nQuiz topics: PPE, tool guards, electrical safety, dust safety, emergency response.",
  "M02-tools": "Understand what each carpentry tool is for and how to keep it accurate. Covers measuring tools, saws, chisels, planes, drills, routers, clamps, sanders, and basic maintenance.\n\nPractical exercise: sharpen a chisel, square a blade, test a drill bit, and create a daily tool checklist.\n\nQuiz topics: tool selection, maintenance, safe operation, clamping, blade and bit care.",
  "M03-measure-mark": "Good carpentry begins with accurate layout. Practice reading drawings, using tape and square correctly, marking reference faces, allowing tolerances, and checking diagonals.\n\nPractical exercise: mark and cut four pieces for a square frame within a 2 mm tolerance.\n\nQuiz topics: tolerances, squareness, reference edges, marking tools, drawing interpretation.",
  "M04-wood-materials": "Study solid wood, plywood, MDF, particle board, laminates, veneers, screws, hinges, channels, adhesives, and how moisture affects material movement.\n\nPractical exercise: compare three board samples, choose hardware for a cabinet, and explain why the choice fits the job.\n\nQuiz topics: wood movement, board selection, adhesives, fasteners, hardware.",
  "M05-cutting-joining": "Build core cutting and joining skill: rip cuts, cross cuts, mitres, curves, dados, rabbets, dowels, pocket screws, mortise and tenon, and basic jigs.\n\nPractical exercise: make a small joined frame using two joinery methods and test it for square and strength.\n\nQuiz topics: saw setup, grain direction, joinery choice, glue-up, clamping pressure.",
  "M06-furniture-basics": "Move from parts to furniture. Learn frame construction, carcass building, shelves, shutters, drawers, edge banding, alignment, and simple ergonomic dimensions.\n\nPractical exercise: build a small wall cabinet or stool with a measured drawing and cutting list.\n\nQuiz topics: carcass layout, drawer clearance, hinges, load paths, assembly order.",
  "M07-finishing": "Learn surface preparation and finish selection: sanding sequence, filling, staining, sealing, polishing, varnish, PU, oil, wax, and protection during transport.\n\nPractical exercise: prepare three sample boards with different finishes and compare appearance, touch, and durability.\n\nQuiz topics: grit sequence, stain control, finish compatibility, defects, curing.",
  "M08-site-installation": "Practice real site work: measurement verification, wall/floor checks, anchoring, leveling, scribing, client communication, snag lists, and handover.\n\nPractical exercise: install a shelf or cabinet mock-up on an uneven wall and create a handover checklist.\n\nQuiz topics: anchors, leveling, site measurement, snag correction, client handover.",
  "M09-repair": "Learn diagnosis and repair: loose joints, swollen shutters, scratches, broken hardware, water damage, laminate peeling, and restoration planning.\n\nPractical exercise: inspect a damaged furniture piece, diagnose the cause, and prepare a repair estimate with steps.\n\nQuiz topics: fault diagnosis, repair sequence, material matching, hardware replacement, prevention.",
  "M10-advanced-craft": "Develop professional judgment: complex joinery, templates, curved work, built-ins, quality inspection, costing, time planning, workshop leadership, and client-ready craftsmanship.\n\nPractical exercise: plan and build a capstone piece with drawing, cutting list, finish schedule, quality checklist, and final presentation.\n\nQuiz topics: advanced joinery, costing, QA, production planning, professional standards.",
};

export function getTakshaSections(moduleId: string): Array<Section & { content: { body: string } }> {
  const mod = TAKSHA_MODULES.find((m) => m.id === moduleId);
  if (!mod) return [];
  return [
    {
      id: `${moduleId}-overview`,
      module_id: moduleId,
      title_en: "Training Brief, Exercises, and Quiz Topics",
      title_bn: "Training Brief, Exercises, and Quiz Topics",
      title_hi: "Training Brief, Exercises, and Quiz Topics",
      sort_order: 1,
      estimated_hours: mod.theory_hours + mod.practical_hours,
      content: { body: moduleBodies[moduleId] || "" },
    },
  ];
}
